export const metadata = {
  title: "Register on ecommerce site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div>How are you its Header</div>
      {children}
      <div>How are you its footer</div>
    </>
  );
}
